import type { Order } from "@/types/entities";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function order(o: Order): Order {
  return o;
}

export const mockOrders: Order[] = [
  order({
    id: "order-1042",
    number: "SI-1042",
    customerName: "Олена Ковальчук",
    phone: "+380671234567",
    email: "olena.k@example.com",
    amount: 3200,
    currency: "UAH",
    status: "new",
    isRead: false,
    orderType: "icon_order",
    items: [
      {
        id: "item-1",
        productId: "product-icon-bogomater-large",
        title: "Ікона «Богоматір Володимирська», велика",
        quantity: 1,
        unitPrice: 3200,
        currency: "UAH",
      },
    ],
    comment: "Просимо доставити до Різдва.",
    statusHistory: [{ id: "hist-1", status: "new", changedAt: daysAgo(0) }],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  }),
  order({
    id: "order-1041",
    number: "SI-1041",
    customerName: "Іван Петренко",
    phone: "+380509876543",
    amount: 1450,
    currency: "UAH",
    status: "new",
    isRead: false,
    orderType: "icon_order",
    items: [
      {
        id: "item-2",
        productId: "product-icon-spas-small",
        title: "Ікона «Спас Нерукотворний», мала",
        quantity: 1,
        unitPrice: 1450,
        currency: "UAH",
      },
    ],
    statusHistory: [{ id: "hist-2", status: "new", changedAt: daysAgo(0) }],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  }),
  order({
    id: "order-1040",
    number: "SI-1040",
    customerName: "Марія Сидоренко",
    phone: "+380631112233",
    email: "maria.s@example.com",
    amount: 300,
    currency: "UAH",
    status: "in_progress",
    isRead: true,
    orderType: "product_order",
    items: [
      { id: "item-3", title: "Молитовник кишеньковий", quantity: 1, unitPrice: 180, currency: "UAH" },
      { id: "item-4", title: "Лампадка скляна", quantity: 1, unitPrice: 95, currency: "UAH" },
    ],
    internalNote: "Клієнтка просила упакувати як подарунок.",
    statusHistory: [
      { id: "hist-3", status: "new", changedAt: daysAgo(3) },
      { id: "hist-4", status: "in_progress", changedAt: daysAgo(1) },
    ],
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  }),
  order({
    id: "order-1039",
    number: "SI-1039",
    customerName: "Андрій Мельник",
    phone: "+380971234567",
    amount: 1200,
    currency: "UAH",
    status: "in_progress",
    isRead: true,
    orderType: "product_order",
    items: [
      { id: "item-5", title: "Набір для хрещення", quantity: 1, unitPrice: 1200, currency: "UAH" },
    ],
    statusHistory: [
      { id: "hist-5", status: "new", changedAt: daysAgo(5) },
      { id: "hist-6", status: "in_progress", changedAt: daysAgo(4) },
    ],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  }),
  order({
    id: "order-1038",
    number: "SI-1038",
    customerName: "Тетяна Бондаренко",
    phone: "+380661239876",
    email: "tanya.b@example.com",
    amount: 650,
    currency: "UAH",
    status: "completed",
    isRead: true,
    orderType: "icon_order",
    items: [
      {
        id: "item-6",
        productId: "product-icon-mykolai-medium",
        title: "Ікона «Микола Чудотворець», середня",
        quantity: 1,
        unitPrice: 650,
        currency: "UAH",
      },
    ],
    statusHistory: [
      { id: "hist-7", status: "new", changedAt: daysAgo(14) },
      { id: "hist-8", status: "in_progress", changedAt: daysAgo(12) },
      { id: "hist-9", status: "completed", changedAt: daysAgo(10) },
    ],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(10),
  }),
  order({
    id: "order-1037",
    number: "SI-1037",
    customerName: "Ольга Ткаченко",
    phone: "+380500001122",
    amount: 220,
    currency: "UAH",
    status: "completed",
    isRead: true,
    orderType: "product_order",
    items: [
      { id: "item-7", title: "Чотки дерев'яні, 33 намистини", quantity: 1, unitPrice: 220, currency: "UAH" },
    ],
    statusHistory: [
      { id: "hist-10", status: "new", changedAt: daysAgo(20) },
      { id: "hist-11", status: "completed", changedAt: daysAgo(18) },
    ],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
  }),
  order({
    id: "order-1036",
    number: "SI-1036",
    customerName: "Сергій Гончар",
    phone: "+380931230000",
    amount: 850,
    currency: "UAH",
    status: "cancelled",
    isRead: true,
    orderType: "product_order",
    items: [
      { id: "item-8", title: "Хрестик натільний, срібло", quantity: 1, unitPrice: 850, currency: "UAH" },
    ],
    internalNote: "Клієнт скасував — знайшов дешевше в іншому місці.",
    statusHistory: [
      { id: "hist-12", status: "new", changedAt: daysAgo(9) },
      { id: "hist-13", status: "cancelled", changedAt: daysAgo(8) },
    ],
    createdAt: daysAgo(9),
    updatedAt: daysAgo(8),
  }),
  order({
    id: "order-1035",
    number: "SI-1035",
    customerName: "Наталія Іванова",
    phone: "+380671110022",
    email: "nataliya.i@example.com",
    amount: 4500,
    currency: "UAH",
    status: "new",
    isRead: false,
    orderType: "custom_request",
    items: [
      { id: "item-9", title: "Індивідуальне написання ікони на замовлення", quantity: 1, unitPrice: 4500, currency: "UAH" },
    ],
    comment: "Хочу замовити ікону св. Пантелеймона розміром 40×50 см.",
    statusHistory: [{ id: "hist-14", status: "new", changedAt: daysAgo(1) }],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  }),
  order({
    id: "order-1034",
    number: "SI-1034",
    customerName: "Роман Литвин",
    phone: "+380661234499",
    amount: 120,
    currency: "UAH",
    status: "in_progress",
    isRead: false,
    orderType: "product_order",
    items: [
      { id: "item-10", title: "Набір церковних свічок (50 шт.)", quantity: 1, unitPrice: 120, currency: "UAH" },
    ],
    statusHistory: [
      { id: "hist-15", status: "new", changedAt: daysAgo(2) },
      { id: "hist-16", status: "in_progress", changedAt: daysAgo(1) },
    ],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  }),
  order({
    id: "order-1033",
    number: "SI-1033",
    customerName: "Юлія Савченко",
    phone: "+380509991122",
    email: "yulia.s@example.com",
    amount: 2100,
    currency: "UAH",
    status: "completed",
    isRead: true,
    orderType: "icon_order",
    items: [
      { id: "item-11", title: "Ікона «Спас Нерукотворний», 20×30 см", quantity: 1, unitPrice: 2100, currency: "UAH" },
    ],
    statusHistory: [
      { id: "hist-17", status: "new", changedAt: daysAgo(30) },
      { id: "hist-18", status: "in_progress", changedAt: daysAgo(27) },
      { id: "hist-19", status: "completed", changedAt: daysAgo(22) },
    ],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(22),
  }),
];
