import type { Order } from "@/types/entities";

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

function order(o: Order): Order {
  return o;
}

export const mockOrders: Order[] = [
  order({
    id: "order-1042",
    orderNumber: "IK-001042",
    customerName: "Олена Ковальчук",
    contactMethod: "phone",
    contactValue: "+380671234567",
    totalPriceCents: 320000,
    currency: "UAH",
    status: "new",
    isRead: false,
    iconId: "icon-bogomater-large",
    iconTitleSnapshot: "Ікона «Богоматір Володимирська», велика",
    iconSlugSnapshot: "bogomater-volodymyrska-velyka",
    items: [],
    comment: "Просимо доставити до Різдва.",
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  }),
  order({
    id: "order-1041",
    orderNumber: "IK-001041",
    customerName: "Іван Петренко",
    contactMethod: "phone",
    contactValue: "+380509876543",
    totalPriceCents: 145000,
    currency: "UAH",
    status: "new",
    isRead: false,
    iconId: "icon-spas-small",
    iconTitleSnapshot: "Ікона «Спас Нерукотворний», мала",
    iconSlugSnapshot: "spas-nerukotvornyi-mala",
    items: [],
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  }),
  order({
    id: "order-1040",
    orderNumber: "IK-001040",
    customerName: "Марія Сидоренко",
    contactMethod: "email",
    contactValue: "maria.s@example.com",
    totalPriceCents: 30000,
    currency: "UAH",
    status: "confirmed",
    isRead: true,
    primaryProductId: "product-molytovnyk",
    primaryProductNameSnapshot: "Молитовник кишеньковий",
    primaryProductSlugSnapshot: "molytovnyk-kyshenkovyi",
    items: [{ id: "item-3", optionId: "opt-lampadka", optionNameSnapshot: "Лампадка скляна", priceCentsSnapshot: 9500, quantity: 1 }],
    adminNote: "Клієнтка просила упакувати як подарунок.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  }),
  order({
    id: "order-1039",
    orderNumber: "IK-001039",
    customerName: "Андрій Мельник",
    contactMethod: "phone",
    contactValue: "+380971234567",
    totalPriceCents: 120000,
    currency: "UAH",
    status: "in_production",
    isRead: true,
    primaryProductId: "product-nabir-hreschennya",
    primaryProductNameSnapshot: "Набір для хрещення",
    primaryProductSlugSnapshot: "nabir-dlya-hreschennya",
    items: [],
    createdAt: daysAgo(5),
    updatedAt: daysAgo(4),
  }),
  order({
    id: "order-1038",
    orderNumber: "IK-001038",
    customerName: "Тетяна Бондаренко",
    contactMethod: "email",
    contactValue: "tanya.b@example.com",
    totalPriceCents: 65000,
    currency: "UAH",
    status: "completed",
    isRead: true,
    iconId: "icon-mykolai-medium",
    iconTitleSnapshot: "Ікона «Микола Чудотворець», середня",
    iconSlugSnapshot: "mykolai-chudotvorets-serednya",
    items: [],
    createdAt: daysAgo(14),
    updatedAt: daysAgo(10),
  }),
  order({
    id: "order-1037",
    orderNumber: "IK-001037",
    customerName: "Ольга Ткаченко",
    contactMethod: "phone",
    contactValue: "+380500001122",
    totalPriceCents: 22000,
    currency: "UAH",
    status: "completed",
    isRead: true,
    primaryProductId: "product-chotky",
    primaryProductNameSnapshot: "Чотки дерев'яні, 33 намистини",
    primaryProductSlugSnapshot: "chotky-derevyani-33",
    items: [],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(18),
  }),
  order({
    id: "order-1036",
    orderNumber: "IK-001036",
    customerName: "Сергій Гончар",
    contactMethod: "phone",
    contactValue: "+380931230000",
    totalPriceCents: 85000,
    currency: "UAH",
    status: "cancelled",
    isRead: true,
    primaryProductId: "product-hrestyk",
    primaryProductNameSnapshot: "Хрестик натільний, срібло",
    primaryProductSlugSnapshot: "hrestyk-natilnyi-sriblo",
    items: [],
    adminNote: "Клієнт скасував — знайшов дешевше в іншому місці.",
    createdAt: daysAgo(9),
    updatedAt: daysAgo(8),
  }),
  order({
    id: "order-1035",
    orderNumber: "IK-001035",
    customerName: "Наталія Іванова",
    contactMethod: "email",
    contactValue: "nataliya.i@example.com",
    totalPriceCents: 450000,
    currency: "UAH",
    status: "contacted",
    isRead: false,
    items: [],
    comment: "Хочу замовити ікону св. Пантелеймона розміром 40×50 см.",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  }),
  order({
    id: "order-1034",
    orderNumber: "IK-001034",
    customerName: "Роман Литвин",
    contactMethod: "phone",
    contactValue: "+380661234499",
    totalPriceCents: 12000,
    currency: "UAH",
    status: "ready",
    isRead: false,
    primaryProductId: "product-svichky",
    primaryProductNameSnapshot: "Набір церковних свічок (50 шт.)",
    primaryProductSlugSnapshot: "nabir-svichok-50",
    items: [],
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  }),
  order({
    id: "order-1033",
    orderNumber: "IK-001033",
    customerName: "Юлія Савченко",
    contactMethod: "email",
    contactValue: "yulia.s@example.com",
    totalPriceCents: 210000,
    currency: "UAH",
    status: "shipped",
    isRead: true,
    iconId: "icon-spas-2030",
    iconTitleSnapshot: "Ікона «Спас Нерукотворний», 20×30 см",
    iconSlugSnapshot: "spas-nerukotvornyi-20x30",
    items: [],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(22),
  }),
];
