import type { Prayer } from "@/types/entities";

const now = new Date().toISOString();

function base(
  overrides: Partial<Prayer> & Pick<Prayer, "id" | "title" | "slug" | "text" | "language" | "prayerType">,
): Prayer {
  return {
    status: "published",
    audioUrl: undefined,
    qrCodeUrl: undefined,
    imageUrl: undefined,
    source: undefined,
    sourceUrl: undefined,
    note: undefined,
    visualizerEnabled: false,
    visualizerImageUrl: undefined,
    particleCountDesktop: 1200,
    particleCountMobile: 400,
    particleSize: 2,
    particleColorMode: "theme",
    backgroundColor: "#0b1220",
    audioReactivity: 0.4,
    sceneTimeline: [],
    subtitleCues: [],
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
}

export const mockPrayers: Prayer[] = [
  base({
    id: "prayer-otche-nash-uk",
    title: "Отче наш",
    slug: "otche-nash",
    text: "Отче наш, Ти що єси на небесах, нехай святиться Ім'я Твоє, нехай прийде Царство Твоє...",
    language: "uk",
    prayerType: "general",
    audioUrl: "/mock-audio/otche-nash.mp3",
    qrCodeUrl: "media-icon-spasitel",
    visualizerEnabled: true,
    visualizerImageUrl: "media-icon-spasitel",
    audioReactivity: 0.6,
    sceneTimeline: [
      { id: "scene-1", atMs: 0, label: "Тиша, поява часток", intensity: 0.2 },
      { id: "scene-2", atMs: 8000, label: "Наростання світла", intensity: 0.7 },
      { id: "scene-3", atMs: 20000, label: "Кульмінація", intensity: 1 },
    ],
    subtitleCues: [
      { id: "cue-1", startMs: 0, endMs: 4000, text: "Отче наш, Ти що єси на небесах," },
      { id: "cue-2", startMs: 4000, endMs: 9000, text: "нехай святиться Ім'я Твоє," },
    ],
  }),
  base({
    id: "prayer-otche-nash-ru",
    title: "Отче наш",
    slug: "otche-nash",
    text: "Отче наш, Иже еси на небесех, да святится имя Твое, да приидет Царствие Твое...",
    language: "ru",
    prayerType: "general",
    audioUrl: "/mock-audio/otche-nash-ru.mp3",
  }),
  base({
    id: "prayer-our-father-en",
    title: "The Lord's Prayer",
    slug: "the-lords-prayer",
    text: "Our Father, who art in heaven, hallowed be Thy Name, Thy Kingdom come...",
    language: "en",
    prayerType: "general",
  }),
  base({
    id: "prayer-ranishnya-uk",
    title: "Ранкова молитва",
    slug: "rankova-molytva",
    text: "Боже, очисти мене грішного, бо ніколи доброго не сотворив я перед Тобою...",
    language: "uk",
    prayerType: "morning",
    source: "Молитовник",
    audioUrl: "/mock-audio/rankova.mp3",
  }),
  base({
    id: "prayer-vechirnya-uk",
    title: "Вечірня молитва",
    slug: "vechirnya-molytva",
    text: "Боже вічний і Царю всякого створіння, що сподобив мене дожити до цієї години...",
    language: "uk",
    prayerType: "evening",
    status: "draft",
  }),
  base({
    id: "prayer-do-mykolaya-uk",
    title: "Молитва до святителя Миколая",
    slug: "molytva-do-svyatytelya-mykolaya",
    text: "О всехвальний угодниче і теплий помічнику, скорий заступниче Миколаю...",
    language: "uk",
    prayerType: "to_saint",
    iconId: "icon-mykolai-uk",
    visualizerEnabled: true,
    visualizerImageUrl: undefined,
  }),
  base({
    id: "prayer-do-spasa-uk",
    title: "Молитва перед іконою Спаса Нерукотворного",
    slug: "molytva-pered-ikonoyu-spasa",
    text: "Господи Ісусе Христе, Спасителю наш, що явив образ лику Твого...",
    language: "uk",
    prayerType: "to_icon",
    iconId: "icon-spasitel-uk",
    calendarDayId: "cal-nativity-uk",
  }),
  base({
    id: "prayer-pered-yizhoyu-uk",
    title: "Молитва перед їжею",
    slug: "molytva-pered-yizheyu",
    text: "Очі всіх на Тебе, Господи, вповають, і Ти даєш їм поживу вчасно...",
    language: "uk",
    prayerType: "before_meal",
  }),
  base({
    id: "prayer-pislya-yizhi-uk",
    title: "Молитва після їжі",
    slug: "molytva-pislya-yizhi",
    text: "Благодаримо Тебе, Христе Боже наш, що насолодив нас земних Твоїх благ...",
    language: "uk",
    prayerType: "after_meal",
    status: "archived",
  }),
  base({
    id: "prayer-do-troitsi-uk",
    title: "Молитва до Святої Трійці",
    slug: "molytva-do-svyatoi-troytsi",
    text: "Пресвята Трійце, помилуй нас; Господи, очисти гріхи наші...",
    language: "uk",
    prayerType: "general",
    iconId: "icon-troitsa-uk",
    visualizerEnabled: true,
    visualizerImageUrl: "media-icon-troitsa",
    particleColorMode: "gradient",
  }),
  base({
    id: "prayer-feast-pokrova-uk",
    title: "Молитва на свято Покрови",
    slug: "molytva-na-svyato-pokrovy",
    text: "Пресвята Богородице, покрий нас чесним Твоїм омофором...",
    language: "uk",
    prayerType: "feast",
    calendarDayId: "cal-pokrova-uk",
    iconId: "icon-pokrova-uk",
  }),
  base({
    id: "prayer-molytva-ranishnya-ru",
    title: "Утренняя молитва",
    slug: "utrennyaya-molytva",
    text: "Боже, очисти мя грешнаго, яко николиже сотворих благое пред Тобою...",
    language: "ru",
    prayerType: "morning",
    status: "draft",
  }),
];
