import type { Product } from "@/types/entities";

const now = new Date().toISOString();

export const mockProducts: Product[] = [
  {
    id: "product-icon-spas-small",
    title: "Ікона «Спас Нерукотворний», мала",
    slug: "ikona-spas-nerukotvorny-mala",
    description: "Писана ікона на липовій дошці, розмір 15×20 см.",
    price: 1450,
    currency: "UAH",
    stockStatus: "in_stock",
    featured: true,
    active: true,
    imageIds: ["media-product-icon-small"],
    categoryId: "cat-icons",
    linkedIconId: "icon-spasitel-uk",
    dimensions: "15 × 20 см",
    materials: "Липа, левкас, темпера",
    productionTimeDays: 0,
    consecrated: true,
    variants: [
      { id: "var-1", label: "15×20 см", sku: "SPAS-15X20" },
      { id: "var-2", label: "20×30 см", priceOverride: 2100, sku: "SPAS-20X30" },
    ],
    seoTitle: "Ікона Спас Нерукотворний купити",
    seoDescription: "Писана ікона Спаса Нерукотворного, освячена, з доставкою по Україні.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-icon-bogomater-large",
    title: "Ікона «Богоматір Володимирська», велика",
    slug: "ikona-bogomater-volodymyrska-velyka",
    description: "Писана ікона у кіоті, розмір 30×40 см.",
    price: 3200,
    currency: "UAH",
    stockStatus: "made_to_order",
    featured: true,
    active: true,
    imageIds: ["media-product-icon-large"],
    categoryId: "cat-icons",
    linkedIconId: "icon-bogomater-uk",
    dimensions: "30 × 40 см",
    materials: "Дерево, левкас, темпера, позолота",
    productionTimeDays: 21,
    consecrated: true,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-icon-mykolai-medium",
    title: "Ікона «Микола Чудотворець», середня",
    slug: "ikona-mykolai-chudotvorets-serednya",
    description: "Друкована ікона на дереві, розмір 20×25 см.",
    price: 650,
    currency: "UAH",
    stockStatus: "in_stock",
    featured: false,
    active: true,
    imageIds: ["media-product-icon-small"],
    categoryId: "cat-icons",
    linkedIconId: "icon-mykolai-uk",
    dimensions: "20 × 25 см",
    materials: "Дерево, друк",
    productionTimeDays: 0,
    consecrated: true,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-molytvennyk",
    title: "Молитовник кишеньковий",
    slug: "molytvennyk-kyshenkovyi",
    description: "Компактний молитовник з основними молитвами українською мовою.",
    price: 180,
    currency: "UAH",
    stockStatus: "in_stock",
    featured: false,
    active: true,
    imageIds: [],
    categoryId: "cat-books",
    productionTimeDays: 0,
    consecrated: false,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-svichky-nabir",
    title: "Набір церковних свічок (50 шт.)",
    slug: "nabir-tserkovnyh-svichok-50",
    description: "Віскові свічки для домашньої молитви.",
    price: 120,
    currency: "UAH",
    stockStatus: "in_stock",
    featured: false,
    active: true,
    imageIds: [],
    categoryId: "cat-candles",
    productionTimeDays: 0,
    consecrated: false,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-lampadka",
    title: "Лампадка скляна",
    slug: "lampadka-sklyana",
    description: "Скляна лампадка для лампадного масла.",
    price: 95,
    currency: "UAH",
    stockStatus: "out_of_stock",
    featured: false,
    active: true,
    imageIds: [],
    categoryId: "cat-candles",
    productionTimeDays: 0,
    consecrated: false,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-hrestyk-sribniy",
    title: "Хрестик натільний, срібло",
    slug: "hrestyk-natilnyi-sriblo",
    description: "Срібний натільний хрестик з гравіюванням.",
    price: 850,
    currency: "UAH",
    stockStatus: "in_stock",
    featured: false,
    active: false,
    imageIds: [],
    categoryId: "cat-jewelry",
    productionTimeDays: 3,
    consecrated: true,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-nabir-hreshchennya",
    title: "Набір для хрещення",
    slug: "nabir-dlya-hreshchennya",
    description: "Хрестильний набір: сорочка, рушник, свічка, хрестик.",
    price: 1200,
    currency: "UAH",
    stockStatus: "made_to_order",
    featured: true,
    active: true,
    imageIds: [],
    categoryId: "cat-gifts",
    productionTimeDays: 7,
    consecrated: false,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-icon-troitsa-draft",
    title: "Ікона «Свята Трійця» (у розробці)",
    slug: "ikona-svyata-troitsa-chernetka",
    description: "Опис товару ще уточнюється.",
    price: 0,
    currency: "UAH",
    stockStatus: "made_to_order",
    featured: false,
    active: false,
    imageIds: [],
    categoryId: "cat-icons",
    linkedIconId: "icon-troitsa-uk",
    consecrated: false,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "product-chotky",
    title: "Чотки дерев'яні, 33 намистини",
    slug: "chotky-derevyani-33",
    description: "Чотки з натурального дерева для молитовного правила.",
    price: 220,
    currency: "UAH",
    stockStatus: "in_stock",
    featured: false,
    active: true,
    imageIds: [],
    categoryId: "cat-jewelry",
    productionTimeDays: 0,
    consecrated: false,
    variants: [],
    createdAt: now,
    updatedAt: now,
  },
];
