'use client';
import {useEffect,useRef,useState} from 'react';
import {Save,Check,EyeOff,Image as ImageIcon} from 'lucide-react';
import {MediaUploadButton} from '@/components/forms/media-upload-button';
import {apiClient} from '@/lib/api';
import {Button} from '@/components/ui/button';
type Version={id:string;original_key:string;marker_key:string;panel_key:string;crop_x:number;crop_y:number;crop_width:number;crop_height:number;identity_verified:number;rights_verified:number;source_url:string;author:string;rights_statement:string};
type State={draft:Version|null;published:Version|null};
const preview=(key:string)=>'/api/bff/marker-images/preview?key='+encodeURIComponent(key);
export function MarkerImageEditor({groupId,mainImage}:{groupId:string;mainImage?:string}){
 const endpoint='/api/bff/marker-images/saint/'+encodeURIComponent(groupId);
 const [state,setState]=useState<State>({draft:null,published:null}),[key,setKey]=useState(''),[image,setImage]=useState<HTMLImageElement|null>(null);
 const [zoom,setZoom]=useState(1),[x,setX]=useState(50),[y,setY]=useState(50),[verified,setVerified]=useState(false),[rightsVerified,setRightsVerified]=useState(false);
 const [source,setSource]=useState(''),[author,setAuthor]=useState(''),[rights,setRights]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),initialCrop=useRef<Version|null>(null);
 const accept=(value:State)=>{setState(value);setDirty(false);};
 useEffect(()=>{const abort=new AbortController();void fetch(endpoint,{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('Не удалось прочитать настройки');return r.json();}).then((value:State)=>{accept(value);const v=value.draft;if(v){initialCrop.current=v;setKey(v.original_key);setVerified(!!v.identity_verified);setRightsVerified(!!v.rights_verified);setSource(v.source_url??'');setAuthor(v.author??'');setRights(v.rights_statement??'');}}).catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[endpoint]);
 useEffect(()=>{if(!key)return;let stopped=false;const loaded=new window.Image();loaded.onload=()=>{if(stopped)return;setImage(loaded);const crop=initialCrop.current;if(crop){const side=crop.crop_width*loaded.width;setZoom(Math.min(loaded.width,loaded.height)/side);setX(loaded.width===side?50:crop.crop_x*loaded.width/(loaded.width-side)*100);setY(loaded.height===side?50:crop.crop_y*loaded.height/(loaded.height-side)*100);initialCrop.current=null;}};loaded.onerror=()=>{if(!stopped){setImage(null);setError('Изображение недоступно');}};loaded.src=preview(key);return()=>{stopped=true;};},[key]);
 const side=image?Math.min(image.width,image.height)/zoom:0,sx=image?(image.width-side)*x/100:0,sy=image?(image.height-side)*y/100:0;
 useEffect(()=>{const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,256,256);if(image)ctx.drawImage(image,sx,sy,side,side,0,0,256,256);},[image,sx,sy,side]);
 function original(value:string){initialCrop.current=null;setKey(value.replace(/^\//,''));setImage(null);setVerified(false);setRightsVerified(false);setZoom(1);setX(50);setY(50);setDirty(true);setError('');}
 async function command(body:unknown){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.details??result.message??'Ошибка');accept(result);}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function derivative(size:number){if(!image)throw Error('Нет исходника');const c=document.createElement('canvas');c.width=c.height=size;c.getContext('2d')!.drawImage(image,sx,sy,side,side,0,0,size,size);const blob=await new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Ошибка миниатюры')),'image/png'));return apiClient.media.uploadObject!({file:new File([blob],`marker-${size}.png`,{type:'image/png'}),module:'saints',entityId:groupId,purpose:'main'});}
 async function save(){if(!image)return;const marker=await derivative(256),panel=await derivative(800);await command({action:'save',draft:{originalKey:key,markerKey:marker.key,panelKey:panel.key,originalWidth:image.width,originalHeight:image.height,crop:{x:sx/image.width,y:sy/image.height,width:side/image.width,height:side/image.height},identityVerified:verified,rightsVerified,source,author,rights}});}
 return <section className="space-y-3 border-t pt-4" aria-label="Изображение метки на глобусе"><h3 className="font-semibold">Изображение метки на глобусе</h3>
 <p data-testid="publication-state">{state.published?'Опубликовано':'Не опубликовано'} · {dirty?'Несохранённые изменения':state.draft?'Черновик сохранён':'Черновика нет'}</p>
 <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={busy||!mainImage||!/^\/?media\//.test(mainImage)} onClick={()=>original(mainImage!)}><ImageIcon/>Основное изображение карточки</Button><MediaUploadButton kind="image" module="saints" entityId={groupId} purpose="main" disabled={busy} onUploaded={({id})=>original(id)} label="Загрузить новый образ"/></div>
 <div className="flex flex-wrap gap-5"><div style={{width:132}}><canvas ref={canvas} width={256} height={256} aria-label="Предпросмотр метки" style={{width:128,height:128,borderRadius:'50%',border:'2px solid #dfb967',background:'#101a20'}}/><div style={{width:0,height:0,borderLeft:'8px solid transparent',borderRight:'8px solid transparent',borderTop:'12px solid #dfb967',margin:'-1px auto 0'}}/></div><div className="min-w-48 flex-1 space-y-2">{[['Масштаб',zoom,1,4,setZoom],['По горизонтали',x,0,100,setX],['По вертикали',y,0,100,setY]].map(([label,value,min,max,setter])=><label className="block" key={String(label)}>{String(label)}<input className="block w-full" aria-label={String(label)} type="range" min={Number(min)} max={Number(max)} step="0.01" disabled={busy||!image} value={Number(value)} onChange={e=>{(setter as (v:number)=>void)(Number(e.target.value));setDirty(true);}}/></label>)}</div></div>
 {[["Источник",source,setSource],["Автор",author,setAuthor],["Условия использования",rights,setRights]].map(([label,value,setter])=><label className="block" key={String(label)}>{String(label)}<input className="block w-full rounded border p-2" aria-label={String(label)} disabled={busy} value={String(value)} onChange={e=>{(setter as (v:string)=>void)(e.target.value);setDirty(true);}}/></label>)}
 <label className="block"><input type="checkbox" checked={verified} disabled={busy||!image} onChange={e=>{setVerified(e.target.checked);setDirty(true);}}/> Изображение соответствует святой</label>
 <label className="block"><input type="checkbox" checked={rightsVerified} disabled={busy||!image} onChange={e=>{setRightsVerified(e.target.checked);setDirty(true);}}/> Права использования проверены</label>
 <div className="flex flex-wrap gap-2"><Button type="button" disabled={busy||!image} onClick={()=>void run(save)}><Save/>Сохранить черновик</Button><Button type="button" disabled={busy||dirty||!state.draft?.identity_verified||!state.draft?.rights_verified} onClick={()=>void run(()=>command({action:'publish',versionId:state.draft?.id}))}><Check/>Опубликовать образ</Button><Button type="button" variant="outline" disabled={busy||!state.published} onClick={()=>void run(()=>command({action:'withdraw'}))}><EyeOff/>Снять с публикации</Button></div>
 {busy?<p role="status">Подготовка изображения…</p>:null}{error?<p role="alert">{error}</p>:null}
 </section>;
}
